version: 2
jobs:
  build:
    docker:
      # Declaring the use of the image
      - image: circleci/node:10.0
    steps:
      - checkout
      - run: echo "my firts test with circle ci"
      - run: npm install
  deploy:
    docker:
      - image: gcr.io/newprotectruben1/googlesdk
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY
          gcloud -v
